Repository freya022/BotCommands, pull requests merged in 2024-05, with the labels that each got.

#168 Wiki: Add components wiki
  wiki/docs/using-components.md
  wiki/mkdocs.yml
  wiki/requirements.txt
  wiki/src/main/java/io/github/freya022/wiki/java/commands/slash/SlashClickGroup.java
  wiki/src/main/java/io/github/freya022/wiki/java/commands/slash/SlashClickerEphemeral.java
  wiki/src/main/java/io/github/freya022/wiki/java/commands/slash/SlashClickerPersistent.java
  wiki/src/main/java/io/github/freya022/wiki/java/filters/ComponentRejectionHandler.java
  wiki/src/main/java/io/github/freya022/wiki/java/filters/GeneralChannelFilter.java
  wiki/src/main/kotlin/io/github/freya022/wiki/commands/slash/SlashClickGroup.kt
  wiki/src/main/kotlin/io/github/freya022/wiki/commands/slash/SlashClickWaiter.kt
  wiki/src/main/kotlin/io/github/freya022/wiki/commands/slash/SlashClicker.kt
  wiki/src/main/kotlin/io/github/freya022/wiki/filters/ComponentRejectionHandler.kt
  wiki/src/main/kotlin/io/github/freya022/wiki/filters/GeneralChannelFilter.kt
Labels: type: documentation, V3

#165 Spring IoC: Fallback to the instance type if getting the bean type fails
  src/main/kotlin/io/github/freya022/botcommands/internal/core/service/InstantiableServices.kt
Labels: bug, V3

#169 Add contextual data to parameter resolvers
  src/main/java/io/github/freya022/botcommands/internal/parameters/resolvers/RoleResolver.java
  src/main/kotlin/io/github/freya022/botcommands/api/core/reflect/ParameterWrapper.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/ClassParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/ParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/ParameterResolverFactory.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/ResolverContainer.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/ResolverData.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/ResolverRequest.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/Resolvers.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/TypedParameterResolverFactory.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/resolvers/ComponentParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/resolvers/ICustomResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/resolvers/IParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/resolvers/MessageContextParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/resolvers/ModalParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/resolvers/SlashParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/resolvers/TextParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/resolvers/UserContextParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/CommandOptions.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/ApplicationCommandInfo.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/ApplicationCommandResolverData.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/context/message/MessageCommandInfo.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/context/message/MessageContextCommandParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/context/user/UserCommandInfo.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/context/user/UserContextCommandParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/slash/AbstractSlashCommandParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/autobuilder/AutoBuilderUtils.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/text/TextCommandParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/handler/ComponentHandlerParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/timeout/TimeoutHandlerParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/modals/ModalHandlerParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/ParameterResolverAdapters.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/resolvers/ChannelResolverFactory.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/resolvers/MemberResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/resolvers/MentionsStringResolverFactory.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/resolvers/RoleResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/resolvers/TimeoutParameterResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/resolvers/localization/LocalizationContextResolverFactories.kt
  src/test/kotlin/doc/kotlin/examples/parameters/MyCustomLocalizationResolverProvider.kt
  src/test/kotlin/io/github/freya022/botcommands/test/resolvers/ListResolver.kt
  src/test/kotlin/io/github/freya022/botcommands/test/resolvers/MapResolver.kt
Labels: type: enhancement, type: breaking, V3

#170 Move component expiration timestamp to the root entity
  src/main/kotlin/io/github/freya022/botcommands/api/components/builder/ITimeoutableComponent.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/data/ComponentTimeout.kt
  src/main/kotlin/io/github/freya022/botcommands/api/core/db/DBResult.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/builder/EphemeralTimeoutableComponentImpl.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/builder/PersistentTimeoutableComponentImpl.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/controller/ComponentController.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/controller/ComponentTimeoutManager.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/data/AbstractComponentData.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/data/ComponentData.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/data/ComponentGroupData.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/data/EphemeralComponentData.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/data/EphemeralTimeout.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/data/PersistentComponentData.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/data/PersistentTimeout.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/repositories/ComponentRepository.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/core/db/DatabaseImpl.kt
  src/main/resources/bc_database_scripts/V3.0.0.2024.05.08__Move_component_timeout.sql
Labels: type: enhancement, type: semi-breaking, V3

#171 Separate custom options and services, add categorizing annotations
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/builder/ApplicationCommandBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/builder/ApplicationCommandOptionAggregateBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/context/annotations/JDAMessageCommand.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/context/annotations/JDAUserCommand.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/context/builder/MessageCommandBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/context/builder/MessageCommandOptionAggregateBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/context/builder/UserCommandBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/context/builder/UserCommandOptionAggregateBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/slash/annotations/JDASlashCommand.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/slash/builder/SlashCommandOptionAggregateBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/builder/ExecutableCommandBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/builder/ServiceOptionBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/text/annotations/JDATextCommandVariation.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/text/builder/TextCommandOptionAggregateBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/text/builder/TextCommandVariationBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/ComponentData.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/ComponentTimeoutHandler.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/GroupTimeoutHandler.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/JDAButtonListener.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/JDASelectMenuListener.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/TimeoutData.kt
  src/main/kotlin/io/github/freya022/botcommands/api/core/options/annotations/Aggregate.kt
  src/main/kotlin/io/github/freya022/botcommands/api/core/options/builder/OptionAggregateBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/modals/annotations/ModalHandler.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/ResolverContainer.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/CommandOptions.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/MethodParameters.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/autobuilder/ContextCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/autobuilder/MessageContextCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/autobuilder/SlashCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/autobuilder/UserContextCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/context/message/MessageCommandInfo.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/context/user/UserCommandInfo.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/slash/SlashCommandInfo.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/autobuilder/AutoBuilderUtils.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/autobuilder/CommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/text/TextCommandVariation.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/text/autobuilder/TextCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/controller/ComponentTimeoutManager.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/controller/ComponentsListener.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/handler/ComponentDescriptor.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/timeout/TimeoutDescriptor.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/core/options/Option.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/modals/ModalHandlerInfo.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/OptionParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/ServiceMethodOption.kt
  src/test/kotlin/doc/kotlin/examples/commands/slash/SlashSayAgainPersistent.kt
  src/test/kotlin/doc/kotlin/examples/commands/slash/SlashSelectRolePersistent.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashDI.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashModal.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashMyCommand.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashNewButtons.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashResolveMentions.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashServiceOption.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashTimeUnit.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/text/TextTest.kt
Labels: type: enhancement, V3

#173 Wiki: Add "extensions" page
  wiki/docs/using-botcommands/extensions.md
  wiki/mkdocs.yml
Labels: type: documentation, V3

#175 Internal resolver container
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/ResolverContainer.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/Resolvers.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/CommandOptions.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/autobuilder/ContextCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/autobuilder/MessageContextCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/autobuilder/SlashCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/autobuilder/UserContextCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/text/TextCommandComparator.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/text/autobuilder/TextCommandAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/handler/ComponentDescriptor.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/modals/ModalHandlerInfo.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/OptionParameter.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/parameters/ResolverContainer.kt
Labels: type: breaking, type: semi-breaking, V3

#174 Update enum resolvers
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/EnumResolver.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/EnumResolverBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/parameters/Resolvers.kt
Labels: type: breaking, V3

#176 Allow anonymous handlers if type-safe binding exists
  src/examples/kotlin/io/github/freya022/bot/commands/slash/SlashButton.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/slash/autocomplete/annotations/AutocompleteHandler.kt
  src/main/kotlin/io/github/freya022/botcommands/api/commands/application/slash/builder/SlashCommandOptionBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/Buttons.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/SelectMenus.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/ComponentTimeoutHandler.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/GroupTimeoutHandler.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/JDAButtonListener.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/annotations/JDASelectMenuListener.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/builder/IActionableComponent.kt
  src/main/kotlin/io/github/freya022/botcommands/api/components/builder/ITimeoutableComponent.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/commands/application/slash/autocomplete/AutocompleteInfoAutoBuilder.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/handler/ComponentHandlerContainer.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/timeout/ComponentTimeoutHandlers.kt
  src/main/kotlin/io/github/freya022/botcommands/internal/components/timeout/GroupTimeoutHandlers.kt
  src/test/kotlin/doc/kotlin/examples/commands/slash/SlashSayAgainPersistent.kt
  src/test/kotlin/doc/kotlin/examples/commands/slash/SlashSelectRolePersistent.kt
  src/test/kotlin/doc/kotlin/examples/commands/slash/SlashTypeSafeButtons.kt
  src/test/kotlin/doc/kotlin/examples/commands/slash/SlashTypeSafeSelectMenus.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashGenerateComponents.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashNewButtons.kt
  src/test/kotlin/io/github/freya022/botcommands/test/commands/slash/SlashNewSelects.kt
Labels: type: enhancement, V3
